name: Docker Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker # use local image for chain builds

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: lychee0
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta vs-ffmpeg-base
        id: meta0
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/vs-ffmpeg-base
          tags: |
            dev

      - name: Build vs-ffmpeg-base
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: vs-ffmpeg-base.dockerfile
          tags: ${{ steps.meta0.outputs.tags }}
          load: true

      - name: Docker meta vs-pytorch
        id: meta1
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/vs-pytorch
          tags: |
            dev
            cuda-dev

      - name: Build vs-pytorch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: vs-pytorch.dockerfile
          tags: ${{ steps.meta1.outputs.tags }}
          load: true
          build-args: |
            BASE_CONTAINER_TAG=dev

      - name: Docker meta vs-playground
        id: meta2
        uses: docker/metadata-action@v5
        with:
          images: |
            lychee0/vs-playground
          tags: |
            dev
            cuda-dev

      - name: Build vs-playground
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          file: vs-playground.dockerfile
          tags: ${{ steps.meta2.outputs.tags }}
          load: true
          build-args: |
            BASE_CONTAINER_TAG=dev
